(TeX-add-style-hook
 "outline"
 (lambda ()
   (TeX-run-style-hooks
    "latex2e"
    "ametsocV5"
    "ametsocV510"
    "amsmath"
    "amsfonts"
    "amssymb"
    "bm"
    "mathptmx"
    "newtxtext"
    "newtxmath")
   (LaTeX-add-labels
    "eq:mse"
    "sec:results"
    "subsec:asym"
    "eq:r1-linear"
    "eq:r1-term1"
    "eq:mse-toasfc"
    "eq:mse-toasfc-approx"
    "eq:sfc-simple"
    "eq:r1-linear2"
    "eq:r1-linear3"
    "eq:r1-linear4"
    "fig:temp-binned-r1"
    "fig:era5-r1-ann"
    "fig:cmip5hist-r1-ann"
    "fig:era5-r1-dev"
    "fig:cmip5hist-r1-dev"
    "fig:era5-r1-decomp-mid"
    "fig:cmip5hist-r1-decomp-mid"
    "fig:era5-r1-decomp-pole"
    "fig:cmip5hist-r1-decomp-pole"
    "fig:echam-rce"
    "fig:echam-rae"
    "fig:malr-mon-lat"
    "fig:dalr-mon-lat"
    "fig:amp-r1-echam")
   (LaTeX-add-bibliographies
    "references"))
 :latex)

