#+TITLE:
#+AUTHOR: Osamu Miyawaki
#+DATE: July 6, 2020
#+OPTIONS: author:nil date:nil toc:nil

* Reviewer 1
Framing the large scale circulation: I did not understand what was meant when you wrote that the "large-scale circulation" contributed to the over-prediction, even after reading lines 65--78 (which I had interpreted as a useful summary of interesting/relevant results by others). I initially thought you were referring to the CO$_2$ effect on the circulation change. But the "large-scale circulation" simply means that a moist adiabatic response should really only be expected in regions of deep convection (and not in regions of large-scale descent). It wasn't until Section 3.2 that I understood what as meant and my reaction to Figure 2 was that "no one expects a moist adiabatic scaling relative to the eastern Pacific surface temperature response." Perhaps making the meaning of "large-scale circulation" more clear with something like this (perhaps the topic sentence(s) or concluding sentence(s) 65--78): "The tropical atmospheric circulation is zonally asymmetric with regions of climatological ascent and descent. Since the tropospheric temperature is only expected to be coupled to the surface temperature in regions of deep atmospheric convection, a moist adiabatic temperature scaling does not necessarily hold in areas of large scale descent or in the tropical average. As such, the presence of the tropical atmospheric circulation may influence the scaling between tropical tropospheric and surface temperature change. In contrast, aquaplanets do not include a tropical, zonally symmetric circulation, and may adhere more closely to moist adiabatic warming throughout the tropics."

This manuscript includes a tremendous amount of information. At times, the many complementary (and subtly different) comparisons can dilute the take home messages. I think it would be extremely useful to try to incorporate the findings into a summary figure that could illustrate the estimated contribution that each process makes to the moist adiabatic warming over-estimation. For example, it is very helpful that you state the contribution to the over-prediction from the circulation and CO$_2$ in the abstract. I don't think you actually state how you arrive at these estimates in the main text. I've constructed a schematic of the type of figure I was thinking of (you could include other simulations, but I think the key is to allow the reader to see the contribution each process makes to the over-prediction). This would essentially combine the information of Figure 1 and 3.

A similar comment regarding the presentation in the text. The average over-prediction values are listed in Sections 3.1--3.3 (rather than the estimate change attributed to each physical process). It would be extremely helpful to 1) re-order the presentation of experiments into a more linear narrative, 2) emphasize a subset of the experiments (and use the others of further evidence of your claims), and 3) focus more on the impact of each process (rather than the mean over-prediction for each experiment). For example, you could:
- start by stating in Section 3.1 that the over-prediction is 23.7\% in abrupt4$\times$CO$_2$ and the magnitude is similar in amipFuture+4$\times$CO$_2$ and amip4K+4$\times$CO$_2$ runs (20.1 and 21.1\%).
- then in Section 3.2, you could state that when you look in regions of deep convection, the abrupt4$\times$CO$_2$ over-prediction drops by 7.1\% to 16.6\%. This is supported by the results from the amipFuture+4$\times$CO$_2$ and amip4K simulations where the overprediction drops by 7.1 and 3.8\%. Last, you could point out that the over-prediction in aqua4K+4$\times$CO$_2$ is similar to the amipFuture+4$\times$CO$_2$ and amip4K+4$\times$CO$_2$ simulations (as you do in lines 292--294).
- in Section 3.3, you could shift your focus to the amipFuture+4$\times$CO$_2$/amipFuture simulations and state that when you remove the direct effect of CO$_2$ the overprediction falls by 3.7\% to 9.3\%. As support, you could note that AMIP and aqua simulations also show declines in the over-prediction when the effects of CO$_2$ changes are removed.
- in section 3.4 you coudl state that entrainment also contributes to the over-prediction (and perhaps state an estimate from the GFDL model experiments).
- this narrative would mean that in each section, you are removing one piece of complexity (first circulation, then CO$_2$, then entrainment) and emphasizing a subset of experiments (e.g., abrupt+amip, and using the others to bolster your claims, e.g., aqua). I think this would make it a bit easier to follow an dunderstand what the many experiments are telling us.

* Reviewer 2
