#+TITLE:
#+AUTHOR: Osamu Miyawaki, Zhihong Tan, Tiffany Shaw, Malte Jansen
#+DATE: July 6, 2020
#+OPTIONS: author:nil date:nil toc:nil num:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry} \usepackage[parfill]{parskip}

* Reviewer 1
To first order, temperature change in the tropical troposphere scales as a moist adiabatic response to greenhouse gas induced surface warming. Miyawaki et al. (2020) show that general circulation models (GCMs) simulate less tropospheric warming in response to changes in atmospheric carbon dioxide than that would be inferred from a moist adiabatic response. They demonstrate three factors contribute to the mismatch between warming inferred from a moist adiabat and GCMs: 1) that a moist adiabatic scaling should hold in regions of deep convection and not the tropics as a whole (referred to as the large-scale circulation in the manuscript), 2) the effects of carbon dioxide changes to on the atmospheric circulation, and 3) the effects of convective entrainment. The results are robust and quantified in a hierarchy of models including a) CMIP5 atmosphere-ocean coupled GCM experiments with a quadrupling of CO\(_2\), b) atmosphere-only simulations responding to an increase in sea surface temperature (SST) and the joint increase of SST and atmospheric CO\(_2\), and c) custom simulations with GFDL AM2 in response to a varied Tokioka parameter (which modifies the model entrainment rate).

This manuscript represents a useful and fundamental contribution to our understanding of the factors contributing to tropical tropospheric temperature change and will likely be well-cited, even though the topic is rather specialized. I really like this paper. While I do not have substantial technical criticisms of the research, I have made a number of editorial suggestions regarding the presentation, which I think will improve the impact of the manuscript. I view this as a recommendation for major, optional revisions, but would strongly encourage the authors to address the essence of my suggestions (I do not expect that the authors will implement the exact changes I suggest).

\textbf{We thank the reviewer for their helpful comments. We revised the manuscript to address many of the concerns they raised. Our responses to their comments are presented in bold. The line numbers referenced in our response correspond to those in the unannotated version of our revised manuscript.}

Framing the large scale circulation: I did not understand what was meant when you wrote that the "large-scale circulation" contributed to the over-prediction, even after reading lines 65--78 (which I had interpreted as a useful summary of interesting/relevant results by others). I initially thought you were referring to the CO\(_2\) effect on the circulation change. But the "large-scale circulation" simply means that a moist adiabatic response should really only be expected in regions of deep convection (and not in regions of large-scale descent). It wasn't until Section 3.2 that I understood what as meant and my reaction to Figure 2 was that "no one expects a moist adiabatic scaling relative to the eastern Pacific surface temperature response." Perhaps making the meaning of "large-scale circulation" more clear with something like this (perhaps the topic sentence(s) or concluding sentence(s) 65--78): "The tropical atmospheric circulation is zonally asymmetric with regions of climatological ascent and descent. Since the tropospheric temperature is only expected to be coupled to the surface temperature in regions of deep atmospheric convection, a moist adiabatic temperature scaling does not necessarily hold in areas of large scale descent or in the tropical average. As such, the presence of the tropical atmospheric circulation may influence the scaling between tropical tropospheric and surface temperature change. In contrast, aquaplanets do not include a tropical, zonally symmetric circulation, and may adhere more closely to moist adiabatic warming throughout the tropics."

\textbf{We revised this paragraph (see lines 69--76) to emphasize that we only expect the moist adiabatic response to hold in regions of deep convection and point to previous work that isolated this region using precipitation weighting.}

This manuscript includes a tremendous amount of information. At times, the many complementary (and subtly different) comparisons can dilute the take home messages. I think it would be extremely useful to try to incorporate the findings into a summary figure that could illustrate the estimated contribution that each process makes to the moist adiabatic warming over-estimation. For example, it is very helpful that you state the contribution to the over-prediction from the circulation and CO\(_2\) in the abstract. I don't think you actually state how you arrive at these estimates in the main text. I've constructed a schematic of the type of figure I was thinking of (you could include other simulations, but I think the key is to allow the reader to see the contribution each process makes to the over-prediction). This would essentially combine the information of Figure 1 and 3.

\textbf{Thank you for the suggestion. Figure 4 now shows a summary of our results and we refer to the specific impacts (in \%) of different contributions on overprediction we cited in the abstract (see lines 297--319). We also revised Section 2.1 and Fig. 1 to emphasize the impacts of the different contributions.}

A similar comment regarding the presentation in the text. The average over-prediction values are listed in Sections 3.1--3.3 (rather than the estimate change attributed to each physical process). It would be extremely helpful to 1) re-order the presentation of experiments into a more linear narrative, 2) emphasize a subset of the experiments (and use the others of further evidence of your claims), and 3) focus more on the impact of each process (rather than the mean over-prediction for each experiment). For example, you could:
- start by stating in Section 3.1 that the over-prediction is \(23.7\%\) in abrupt4\(\times\)CO\(_2\) and the magnitude is similar in amipFuture+4\(\times\)CO\(_2\) and amip4K+4\(\times\)CO\(_2\) runs (\(20.1\) and \(21.1\%\)).
- then in Section 3.2, you could state that when you look in regions of deep convection, the abrupt4\(\times\)CO\(_2\) over-prediction drops by \(7.1\%\) to \(16.6\%\). This is supported by the results from the amipFuture+4\(\times\)CO\(_2\) and amip4K simulations where the overprediction drops by \(7.1\) and \(3.8\%\). Last, you could point out that the over-prediction in aqua4K+4\(\times\)CO\(_2\) is similar to the amipFuture+4\(\times\)CO\(_2\) and amip4K+4\(\times\)CO\(_2\) simulations (as you do in lines 292--294).
- in Section 3.3, you could shift your focus to the amipFuture+4\(\times\)CO\(_2\)/amipFuture simulations and state that when you remove the direct effect of CO\(_2\) the overprediction falls by \(3.7\%\) to \(9.3\%\). As support, you could note that AMIP and aqua simulations also show declines in the over-prediction when the effects of CO\(_2\) changes are removed.
- in section 3.4 you could state that entrainment also contributes to the over-prediction (and perhaps state an estimate from the GFDL model experiments).
- this narrative would mean that in each section, you are removing one piece of complexity (first circulation, then CO\(_2\), then entrainment) and emphasizing a subset of experiments (e.g., abrupt+amip, and using the others to bolster your claims, e.g., aqua). I think this would make it a bit easier to follow an dunderstand what the many experiments are telling us.

\textbf{Thank you for the suggestion. We revised the text to better focus on quantifying the individual contributions. Section 2.1 now includes more discussion on how we separate the effects. We revised the presentation of the results (see Section 3, Fig. 1 and 4) following the reviewer's suggestion.}

Title: You do a bit more than "quantify." You could consider noting that you identify key processes contributing to the over-estimation.

\textbf{We revised the title following the reviewer's suggestion.}

Key Point 2 / Line 19: Consider "after accounting for the presence of a large-scale climatological circulation and the direct effect of CO\(_2\) on circulation changes".

\textbf{We implemented the first part of the reviewer's suggestion (by adding "the presence of" to clarify the statement, see line 10) but decided to leave out the second suggestion ("on circulation changes"). As we discuss in the paper, the direct effect of CO\(_2\) also influences the temperature response through changes in the radiative energy balance and convection in addition to changes in the large-scale circulation. As we do not identify which of these processes dominate the direct CO\(_2\) response in this paper, we prefer to keep the text as is to include all possible processes in the direct CO\(_2\) effect.}

Line 15: Consider making it clear that warming is amplified relative to the surface (or lower troposphere) by inserting "surface." Here you say that the amplification is in response to CO\(_2\) increases, but in other places you are careful to say that it is due to surface warming (and not the direct effect of CO\(_2\)). Maybe you could address this subtlety with "greenhouse warming" in place of "increased CO\(_2\)"?

\textbf{Revised text following the reviewer's suggestion (see line 15).}

Line 21: It wasn't immediately clear how to interpret these numbers, because the range of overprediction is large across CMIP5. So this would account for \(\approx40\%\) or \(\approx75\%\) of the over-prediction, depending on the CMIP5 model considered.

\textbf{We now provide the model hierarchy range of the contribution of the large-scale circulation and direct CO$_2$ effect (see line 21) to be consistent with the earlier presentation of overprediction across the model hierarchy (see line 17).}

Plain Language Summary: There are some places where this reads a bit jargon-y and emphasizes detailed, field specific results rather than broader take-home messages. Consider simplifying this a bit and/or focusing on the implications for the research. For example, you could center the discussion around rising plumes (which leads to thermodynamic heating as water vapor condenses into clouds and rain droplets). This would allow you to substitute out some specialty-specific language such as "mixing of dry environmental air into moist ascent" into something like "dry air mixes into the rising plume, which dilutes the water vapor content and reduces warming from condensation." I view this as an optional editorial comment since plain-language summaries are new enough where there isn't a standard on which audience these should be geared to.

\textbf{Thank you for the suggestion. We revised the Plain Language Summary with a narrative based on rising plumes as the reviewer suggested. The revised summary should be more accesible to a broader audience.}

Line 16, 30, 47: Consider in one or more places clarifying that this is increased "atmospheric" CO\(_2\).

\textbf{Revised text following the reviewer's suggestion (see line 46).}

Line 21: I wasn't initially sure how to interpret this. It would be helpful to say that these values are the multimodel average contributions to the over-prediction.

\textbf{Revised text following the reviewer's suggestion (see line 21).}

Line 50: One paper that is useful to demonstrating this in models is cite:santer_amplification_2005, because it shows that amplification occurs relative to surface warming irrespective of timescale.

\textbf{Added reference following the reviewer's suggestion (see lines 49--50).}

Line 48--51: Use a comma in place of the first and ("and" is used twice in this sentence). Consider inserting "...and *high-resolution* cloud-resolving models (CRMs)..."

\textbf{Revised text following the reviewer's suggestion (see line 50).}

Line 53: Here or at the discussion of the cite:andrews_dependence_2018 paper. I think a useful point to add that the stability also affects the cloud response (e.g., cite:zhou_impact_2016).

\textbf{Revised text and added reference following the reviewer's suggestion (see line 54).}

Line 60--62: This is a useful example, but will be sensitive to the assumptions (e.g., boundary layer relative humidity and the surface temperature). Consider appending your assumptions, e.g., ("...predicts warming aloft of 10 K (for a typical tropical surface temperature of XXX K and a relative humidity of YY%.)")

\textbf{Revised text following the reviewer's suggestion. Note that previously, we obtained the predicted warming of 10 K aloft by using the CMIP5 multi-model mean response of surface temperature and relative humidity as the boundary condition. In the revised text, the slightly different predicted warming of 9 K arises due to the simpler assumption of 4 K warming starting at a surface temperature of 298 K and a fixed relative humidity of \(80\%\) (see lines 61--63).}

Line 68: Consider referencing cite:sobel_enso_2002, which I believe motivated some of the work that you cite.

\textbf{Added reference following the reviewer's suggestion (see lines 75--76).}

Line 75--76: Consider inserting "*largely* confined" since this isn't evident from their Figure 5 (though they do say "largely confined" in their text).

\textbf{We removed this sentence in the revised paragraph (see lines 69--76).}

Line 79 onwards: I was unclear about what you meant by the "direct effect of CO\(_2\)." Is this the "fast response"? I don't think this was adequately defined. You might re-frame this, while simultaneously defining what you mean by the direct effect: "Changes in carbon dioxide result in changes in precipitation and the atmospheric circulation in the absence of surface temperature change cite:bony_robust_2013. This so-called direct effect of CO\(_2\) on atmospheric temperature change is nearly uniform in height..."

\textbf{We added text defining the direct and indirect CO$_2$ effects (see lines 63--68).}

Line 79--84: Should this be described as a circulation/precipitation response? The aquaplanet model shows a similar profile of response (but has no zonally asymmetric circulation in the deep tropics). Could this be alternatively described as the atmosphere coming into balance (with the radiative effects of CO\(_2\)) with a different atmospheric temperature profile?

cite:wang_understanding_2020 \textbf{show that the temperature response associated with the atmosphere coming into a new radiative energy balance with increased in CO$_2$ plays an important role in addition to the influence of energy advected by the change in large-scale circulation and convection. We revised the text to include the influence of the radiative effect (see lines 79--81).}

Line 90--91: Consider "unvarying" instead of "climatological"

\textbf{We rephrased "climatological "to "fixed" (see line 88).}

Line 98: Consider inserting "...in response to *greenhouse gas-induced surface* warming" [I realize you don't force all experiments with CO\(_2\) changes, but you classify the AMIP style experiments as characterizing the "indirect effect of CO\(_2\) change" so I think this may still apply]

\textbf{We rephrased "in response to warming" to "in response to increased CO\(_2\)" since we are quantifying the overprediction of the total response (see line 98).}

Line 107: Define CMIP5

\textbf{Defined the acronym CMIP5 (see line 103).}

Line 107--109: Consider clarifying these are experiments, with language like "...in 29 models using the abrupt\(4\times\)CO\(_2\) and piControl experiments, respectively."

\textbf{We now refer to these simulations as AOGCM experiments following the reviewer's suggestion (see lines 110--111).}

Line 113--114: It isn't clear what "indirect effect" of CO\(_2\) increase is and this is the first time you use the term. Perhaps you could explain the meaning in the introduction (I assume it is the surface warming response to CO\(_2\)).

\textbf{The indirect effect indeed refers to the surface warming effect. We revised the introduction (see lines 63--68) to clarify this terminology.}

Line 115: I was confused by amipF. Is this officially "amipFuture"?

\textbf{We used amipF as an abbreviation for amipFuture in the original manuscript. We now refer to the amipFuture response as AGCMp, which we define in the text (see lines 114--115).}

Line 115--119: Similar to the comment at line 107, perhaps you could simply add "experiment," e.g., "(amip4K *experiment*)"

\textbf{We now refer to these simulations as AGCM experiments following the reviewer's suggestion (see line 112).}

Line 123: This is a little unclear. Is the qObs information important to note here? If so, maybe just add a couple sentences to explain this. I assume the SSTs were derived from an aquaplanet with a mixed layer ocean with some prescribed heat flux (qObs)?

\textbf{We added a sentence describing the Qobs profile (see lines 160--162). The Qobs profile is given by an analytical formula (see} cite:neale_standard_2000 \textbf{for the exact expression) that closely matches the observed zonal SST distribution.}

Line 135--136: This is a useful point to make and a good way to motivate the values you chose. Consider including other works here or perhaps in the introduction (cite:jang_simulation_2013, cite:ham_what_2013, cite:kim_ninosouthern_2011).

\textbf{Revised text and added references following the reviewer's suggestion (see lines 144--145).}

Line 142--143: Above, you say that this parameter only comes into play for plumes rising above 500 hPa. If most of the variations in the entrainment occur above 500 hPa when varying \(\alpha\), consider just averaging above 500 hPa.

\textbf{While $\alpha$ only affects plumes that rise above 500 hPa, it affects the entrainment rate for those plumes at all levels. Thus, there are significant variations in entrainment below 500 hPa as well. Convective parcels move upward, so changes in the entrainment rate below 500 hPa affect the temperature response at 300 hPa. Thus, we prefer to keep the average from 850--200 hPa.}

Line 155--158: Consider breaking this into two sentences: "We compare the tropical tropospheric temperature response to surface warming in aquaplanet models and zero-buoyancy bulk-plume models subject to varying entrainment rates. We consider bulk-plume models from ..."

\textbf{Revised text following the reviewer's suggestion (see lines 168--172).}

Line 166: Consider replacing "to be" with "which is" or "so that the R16 model is"

\textbf{Revised text following the reviewer's suggestion (see line 180).}

Line 168: Replace "the literature." with "each model's respective publication." (assuming this is the case)

\textbf{Revised text following the reviewer's suggestion (see line 185).}

Line 170: I assume this is tropical? 20 N--S? Over land and ocean? Or was this done at each grid cell? Suggest specifying a bit more here.

\textbf{We calculate the moist adiabat at each grid cell, then take the tropical average. We clarified this in the text (see line 187).}

Eq. 2: This isn't exactly what is on the AMS website, but I trust that it is equivalent.

\textbf{The two equations are mathematically equivalent as} \(\epsilon=\frac{R_d}{R_v}\) \textbf{and} \(\Gamma_d=\frac{g}{c_{pd}}\)\textbf{. We now define the expression of \(\Gamma_d\) in the text to make this more clear (see line 195).}

SI Table 2, 4, 5: should this be "indistinguishable from zero"?

\textbf{Corrected captions for Supplementary Tables S4 and S5 (the original Supplementary Table S2 was removed in this revision).}

Line 185--186: It would be very useful to look at this and include a statement that this assumption does not matter. I think cite:flannaghan_tropical_2014 include the effects of freezing in their appendix.

\textbf{We evaluated the moist adiabat including the ice phase following} cite:flannaghan_tropical_2014 \textbf{ (Supplementary Tables S2 and S3). We find that freezing does not significantly change our results and added this statement in the text (see lines 205--207).}

Line 199--200: I think this means that you use each model's vertical velocity field to derive ascent regions (not a multimodel average)?

\textbf{Correct, the ascent regions are derived separately for each model (see lines 125--126). We do this to account for differences in ascent regions across models. However, we show the multi-model mean ascent region for illustrative purposes in Figure 2.}

Line 207: It seems like it would be useful to point this out in Section 3.3: isn't this table essentially showing that CO\(_2\) is important? If you reference this in Section 3.3, it might be worthwhile to analyze the overprediction in regions of ascent (since you will have already discussed the large-scale circulation component).

\textbf{We removed this text and the corresponding table (previously Supplementary Table S2) as it does not fit in the narrative of the revised text.}

Line 209 / Figure 1: I would encourage you to start with the amipFuture\(+4\times\)CO\(_2\), amip4K\(+4\times\)CO\(_2\), and aqua4K\(+4\times\)CO\(_2\) results, which are more comparable to abrupt\(4\times\)CO\(_2\). This would help with the flow as you get to Section 3.3. See major comments.

\textbf{As discussed in our response to the major comments, we revised Section 3 such that we begin by presenting the total overprediction across the model hierarchy.}

Line 222: Consider saying "smaller" in regions of deep convection (since you go on to show that other factors matter and there is still substantive over-prediction).

\textbf{Revised text following the reviewer's suggestion (see line 227).}

Line 225--227: One point that isn't made in this paper is that the tropical upper tropospheric warming should be relatively uniform and so some of these pattern effects (e.g., imperfect scaling in the eastern Pacific) is due to the remote influence of the tropical western Pacific over the eastern Pacific surface.

\textbf{This discussion would be useful for understanding what sets the temperature response in regions of descent. If the weak temperature gradient approximation sufficiently holds above the boundary layer in the deep tropics, one would predict that free-tropospheric warming over regions of descent is set remotely by regions of deep convection. However, as the main focus of our paper is to test the moist adiabatic prediction where we most expect it to hold, we decided to leave detailed discussions pertaining to the response over regions of descent for future work.}

Line 240--241: Please state the experiment you are using. I assume these are the amip4K\(+4\times\)CO\(_2\) experiments, but it's also possible you are quantifying this as the difference between the (amip\(4\times\))CO\(_2\) minus amip4K simulations. Where do you use the amip\(4\times\)CO\(_2\) experiment (mentioned in line 118)?

\textbf{We revised Section 2.1 to describe how we quantify the direct CO\(_2\) effect using the experiment names (see lines 114--118).}

Line 246: Consider replacing "non-zero" with "the".

\textbf{We removed this phrase in the revised sentence (see line 252--254).}

Figure 4: Consider plotting the moist adiabat for reference.

\textbf{We added the moist adiabat as thick black lines to Fig. 3a and b (previously Fig. 4a and b).}

Line 269: Do you know why this scales with the logarithm of entrainment?

\textbf{We included the simple entraining plume models as a first step toward understanding this relationship. However, the fact that even these simple models show a relationship between entrainment and overprediction that is not quite logarithmic (there is some curvature in the black lines in Fig. 3c and d) suggests the answer may be complicated. Our results show the presence of a large-scale circulation may be playing an important role in this relationship as the correlation is stronger with it (\(R=0.98\)) than without (\(R=0.95\)). Establishing the robustness of this relationship in GCMs with various convection schemes and CRMs is an important next step, which we leave for future investigation (see lines 329--331).}

Line 289: It would be worthwhile to quantify the average contribution of the circulation by taking the difference of the over-prediction in the tropical average and the ascent region. Actually, I see you do this in the abstract, so it should also be quantified in the text/conclusion.

\textbf{As we describe in the response to the major comments, we revised the text to emphasize the contribution of the circulation (see line 238).}

Line 295: Similar comment. You could quantify this with (amip4K\(+4\times\)CO\(_2\) minus amip4K, amipF\(+4\times\)CO\(_2\) minus amipF, and aqua4K\(+4\times\)CO\(_2\) minus aqua4K).

\textbf{We revised the text to emphasize the contribution of the direct CO\(_2\) effect (see line 248).}

Line 300: Similar comment. Could you look at the y-intercept in Figure 4c and 4d versus the overprediction from the standard entrainment value to estimate the impact of entrainment? Or perhaps you can turn entrainment to zero in the bulk-plume models?

\textbf{The bulk-plume models simplify to a moist adiabat when the entrainment rate is set to 0, so the overprediction inferred by those models are entirely due to entrainment. Isolating the contribution of entrainment in the GFDL model is not straightforward as the Tokioka parameter only sets the minimum entrainment rate in the RAS scheme. That is, we cannot use the Tokioka parameter to turn off entrainment in the RAS scheme. Furthermore, as the x-axis in Fig. 3c,d (previously 4c,d) is in logarithmic scale, we are unable to extrapolate the data to infer the contribution of entrainment on overprediction.}

Line 317--320: Why was it not included here? Is it complicated to use or have a lot of free parameters that would complicate the story?

\textbf{The model of Singh et al. (2019) requires additional inputs (vertical profiles of convective mass flux, vertical velocity, entrainment rate, and a parameter quantifying the re-evaporation of condensates) compared to the simpler bulk-plume models of SO13, R14, R16, and ZX19. As there are many degrees of freedom in setting the parameters for the Singh et al. (2019) model, it is not trivial to fit their model to the GFDL results. Thus, we prefer to investigate their model in future work.}

Figure S5 and similar box and whisker plots: Is the range of the blue lines the \(5\)--\(95\%\) CI and the red box +/- one standard deviation? The caption seems reversed.

\textbf{While the caption labels were correct, we removed the \(5\)--\(95\%\) confidence interval (CI)} \emph{of the mean} \textbf{and the standard deviation of the distribution from these figures as we do not discuss these statistics in the text (see Fig. 1 and Supplementary Fig. S3 and S4).}

\newpage

* Reviewer 2

The paper investigates the deviation in the upper-troposphere warming from a simple moist-adiabat prediction. It shows that moist adiabat over-predicts the upper-tropospheric warming because of effects from large-scale circulation, direct CO\(_2\) effect, and entrainment. The results are overall convincing but there are a few key points that need to be clarified.

\textbf{We thank the reviewer for their helpful comments. We revised the manuscript to address many of the concerns they raised. Our responses to their comments are presented in bold. The line numbers referenced in our response correspond to those in the unannotated version of our revised manuscript.}

Line 170: The moist adiabatic profile is sensitive to where the air parcel is initially lifted from. The paper chooses the 2 m level. What if using the boundary-layer mean or 950 hPa. The paper should discuss about this sensitivity.

\textbf{We added an analysis of overprediction with the moist adiabat initiated at 950 hPa (see Supplementary Table S2 and S3). We find that our results do not significantly change when the moist adiabat is initiated using 950 hPa temperature and relative humidity and mention this in Section 2.3 (see lines 192--194).}

Line 240--243: I am confused about why the direct CO\(_2\) effect increases over-prediction. The direct CO\(_2\) warms the tropospheric temperature but has little effect on the surface temperature. It indicates that direct CO\(_2\) effect will reduce the over-prediction. I then look at Fig. S2. It shows that while the near-surface temperature only warms by \(\approx0.1\) C, the upper tropospheric temperature following the moist adiabat warms by \(0.5\) C. This amplification (5 times) is much larger than the 2.5 times amplification in other cases (Fig. S1). Why the moist adiabatic amplification is so different?

\textbf{The overprediction by the direct effect is amplified by changes in relative humidity (RH). This increase in RH leads to a lower lifted condensation level (LCL) in the warmer climate. A lower LCL with warming corresponds to enhanced tropospheric warming as predicted by the moist adiabat as the parcel begins to release latent heat at a lower altitude where the saturation vapor pressure is higher. When RH is held fixed at its climatological value, tropospheric warming weakens (see Supplementary Fig. S5) and the amplification is approximately 2.5\(\times\) at 300 hPa, which is comparable to the other cases. Whereas the small change in RH plays a secondary role for the response of the moist adiabat to the indirect effect of CO\(_2\) (SST increase), it plays an important role for the response to the direct CO\(_2\) effect where near-surface warming is small. We now include a discussion of this in Section 3.3 (see lines 254--256).}

Line 155: I am not sure if the zero-buoyancy bulk-plume model is sufficient or accurate enough to explain the temperature deviation in models. By assuming a bulk-plume with constant entrainment rate, the model does not predict the right vertical profile of the temperature deviation from the moist adiabat (see Fig. 2 of cite:zhou_conceptual_2019 for details). In particular, it predicts largest temperature deviation from the moist adiabat in the tropopause, while in reality the tropopause temperature is close to the moist adiabat (that is, overprediction should be nearly zero in the tropopause). It makes more sense to understand the GCM results using the spectral-plume model, as in cite:zhou_conceptual_2019.

\textbf{We added the} cite:zhou_conceptual_2019 \textbf{, hereafter ZX19, model to the revised manuscript with the same parameters as used in their paper (see Fig. 3c,d, Supplementary Fig. S6c,d). Altering the parameters does not substantially change the results. We find that ZX19 exhibits a similar sensitivity of overprediction to entrainment compared to the bulk-plume models of SO13 and R14 and discuss this in the text (see lines 279--281). Our interpretation of this is that the pressure level where we evaluate the overprediction (300 hPa) is sufficiently below the tropopause that the bulk-plume models are also accurate for predicting the temperature response in RCE.}

Line 142: How is the convective entrainment quantified at each level?

\textbf{We use the convective entrainment output directly by the RAS scheme in units of 1/m on the standard output pressure levels for the GFDL model. We rephrased this sentence for clarity (see lines 154--156).}

Line 243: Will it be better to put Fig. 3 together with Fig. 1a,b to better illustrate the changes.

\textbf{We revised Fig. 1 to include the information from Fig. 3 and organized the plots to better illustrate the influence of the large-scale circulation and the direct CO\(_2\) effect. We also created a new figure to summarize our results (see Fig. 4).}

bibliographystyle:apalike
bibliography:/mnt/c/Users/omiyawaki/Sync/papers/references.bib
