* Original version
Title: Climatology of radiative-convective and radiative-advective equilibria in observations and models

Understanding the climatological temperature structure in the latitude-height space has important implications for convective storms in the tropics, baroclinic instability in the midlatitudes, and the global lapse-rate feedback in response to increased CO2. Predicting the latitude-height vertical temperature profile requires running a general circulation model simulation that considers the influence of radiative cooling, advective heat transport by large-scale and parameterized convective motion, and latent heat of condensation on temperature. As a first step toward understanding the vertical temperature structure at various latitudes, we consider simple 1-D models of the vertical temperature structure in the limit of radiative-convective equilibrium (RCE) and radiative-advective equilibrium (RAE). Here, we use the vertically-integrated moist static energy budget to diagnose the spatio-temporal structure of RCE and RAE. We find that RCE exists yearround in the deep tropics and in the northern hemisphere summer in the midlatitudes. RAE exists yearround in both the northern and southern hemisphere high latitudes. We plan to test the hypothesis that 1) RCE in the northern hemisphere midlatitudes occurs due to larger surface turbulent fluxes over land and 2) the equatorward edge of RAE is determined by the extent of sea-ice cover. We will use slab-ocean aquaplanet experiments to test these hypotheses. Furthermore, we hope to show that the temperature profiles predicted from the simple models of RCE and RAE agree with the climatological temperature profile over the respective regions in observations and models.

* Second version
Title: When and where on the modern Earth do Radiative-Convective and Radiative-Advective Equilibrium regimes occur?

Heat-transfer regimes define Earth's modern climate and form the basis of simplified models used to understand climate change. For example, Radiative-Convective Equilibrium (RCE) and Radiative-Advective Equilibrium (RAE) are the standard models for investigating tropical and polar climate change, respectively. Currently we do not have a complete understanding of what controls spatio-temporal changes of heat-transfer regimes. Here we use the vertically-integrated Moist Static Energy budget to define a non-dimensional number that can be used to quantify where RCE and RAE regimes occur in observations and models. We then quantify the seasonality of RCE and RAE regimes in observations and find RCE exists year-round in the deep tropics and in the Northern midlatitudes during summertime. We find RAE exists year-round poleward of ~60 degrees latitude. We also show that the observed RCE and RAE regimes are consistent with a moist adiabatic and stable near-surface temperature profile, respectively. Finally, we vary the mixed layer depth in idealized aquaplanet model simulations with thermodynamic sea ice to test the following hypotheses. 1) The equatorward edge of the RAE regime is determined by the sea ice edge and 2) the RCE regime occurs during midlatitude summer for land-like (small heat capacity) surface conditions.

* Third version
Title: When and where do Radiative-Convective and Radiative-Advective Equilibrium regimes occur on modern Earth?

Conceptual models of an atmospheric column form the basis of simplified models used to understand the vertical temperature profile and their influence on climate change. For example, Radiative-Convective Equilibrium (RCE) and Radiative-Advective Equilibrium (RAE) are the standard idealized models for investigating tropical and polar climate change, respectively. Currently we do not have a complete understanding of the spatio-temporal structure of RCE and RAE. Here we use the vertically-integrated Moist Static Energy budget to define a non-dimensional number that quantifies when and where RCE and RAE are approximately satisfied in observations and models. We find RCE exists year-round in the deep tropics and in the Northern midlatitudes during summertime. RAE exists year-round poleward of ~60 degrees latitude. We show the observed stratification in RCE and RAE regimes are consistent with a moist adiabatic and stable near-surface temperature profile, respectively. Finally, we vary the mixed layer depth in idealized aquaplanet model simulations with thermodynamic sea ice to test the following hypotheses: 1) the RCE regime occurs during midlatitude summer for land-like (small heat capacity) surface conditions and 2) The equatorward edge of the RAE regime is determined by the sea ice edge.

* Final version
Title: When and where do Radiative-Convective and Radiative-Advective Equilibrium regimes occur on modern Earth?

Conceptual models of an atmospheric column provide a basis to understand the vertical temperature profile and its response to climate change. Specifically, Radiative-Convective Equilibrium (RCE) and Radiative-Advective Equilibrium (RAE) are the standard idealized models for investigating tropical and polar climate change, respectively. Currently we do not have a complete understanding of the spatio-temporal structure of RCE and RAE. Here we use the vertically-integrated Moist Static Energy budget to define a non-dimensional number that quantifies when and where RCE and RAE are approximately satisfied in observations and models. We find RCE exists year-round in the deep tropics and in the northern midlatitudes during summertime. RAE exists year-round poleward of ~60 degrees latitude. We show the observed stratification in RCE and RAE regimes are consistent with a moist adiabatic and stable near-surface temperature profile, respectively. Finally, we vary the mixed layer depth in idealized aquaplanet model simulations with thermodynamic sea ice to test the following hypotheses: 1) the RCE regime occurs during midlatitude summer for land-like (small heat capacity) surface conditions and 2) the equatorward edge of the RAE regime is determined by the sea ice edge.
